
'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import SalesChart from "@/components/dashboard/sales-chart"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import PurchaseAnalysisChart from "@/components/reports/purchase-analysis-chart"
import InventoryValueChart from "@/components/reports/inventory-value-chart"
import CommissionReport from "@/components/reports/commission-chart"
import FinancialsChart from "@/components/reports/financials-chart"
import IncomeExpenseChart from "@/components/reports/income-expense-chart"
import ProductPerformanceChart from "@/components/reports/product-performance-chart"
import SupplierSpendChart from "@/components/reports/supplier-spend-chart"
import SalaryReportChart from "@/components/reports/salary-report-chart"

export default function ReportsPage() {
  return (
    <div className="space-y-6">
        <Card>
            <CardHeader>
                <CardTitle>Comprehensive Reports</CardTitle>
                <CardDescription>
                A complete overview of your business performance across all key areas.
                </CardDescription>
            </CardHeader>
        </Card>
        <Tabs defaultValue="sales" className="grid grid-cols-1 gap-6">
            <TabsList className="grid w-full grid-cols-1 h-auto sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
                <TabsTrigger value="sales">Sales</TabsTrigger>
                <TabsTrigger value="purchasing">Purchasing</TabsTrigger>
                <TabsTrigger value="inventory">Inventory</TabsTrigger>
                <TabsTrigger value="financials">Financials</TabsTrigger>
                <TabsTrigger value="commissions">Commissions</TabsTrigger>
            </TabsList>
            <TabsContent value="sales">
                <div className="grid gap-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Sales Report</CardTitle>
                            <CardDescription>
                            An overview of your company's sales performance over the last year.
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="h-[400px]">
                            <SalesChart />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                            <CardTitle>Product Performance</CardTitle>
                            <CardDescription>
                            Revenue generated by each product.
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="h-[400px]">
                            <ProductPerformanceChart />
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>
            <TabsContent value="purchasing">
                <div className="grid gap-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Purchase Order Analysis</CardTitle>
                            <CardDescription>
                            Track purchase order volume and spending over time.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-[400px]">
                                <PurchaseAnalysisChart />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                            <CardTitle>Supplier Spend Analysis</CardTitle>
                            <CardDescription>
                            Total amount spent per supplier.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-[400px]">
                                <SupplierSpendChart />
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>
            <TabsContent value="inventory">
                <Card>
                <CardHeader>
                    <CardTitle>Inventory Report</CardTitle>
                    <CardDescription>
                    Value of your finished goods inventory.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="h-[400px]">
                        <InventoryValueChart />
                    </div>
                </CardContent>
                </Card>
            </TabsContent>
            <TabsContent value="financials">
                 <div className="grid gap-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Income vs. Expense</CardTitle>
                            <CardDescription>Monthly income compared to expenses.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-[400px]">
                                <IncomeExpenseChart />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                            <CardTitle>Accounts Receivable vs. Payable</CardTitle>
                            <CardDescription>
                            Overview of money owed to you vs. money you owe.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-[400px]">
                                <FinancialsChart />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                            <CardTitle>Salary Payments Report</CardTitle>
                            <CardDescription>
                            Total salary paid out per month.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-[400px]">
                                <SalaryReportChart />
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>
            <TabsContent value="commissions">
                <Card>
                <CardHeader>
                    <CardTitle>Distributor Commission Report</CardTitle>
                    <CardDescription>
                    Total commission generated per distributor.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="h-[400px]">
                        <CommissionReport />
                    </div>
                </CardContent>
                </Card>
            </TabsContent>
        </Tabs>
    </div>
  )
}
